version: "3.3"

networks:
  kafkanet:
    driver: overlay
    attachable: true

volumes:
  kafka-dist: {}
  configs: {}
  certs: {}

services:
  zookeeper:
    image: "zk"
    ports:
      - "2181:2181"
    networks:
      kafkanet:
        aliases:
          - zookeeper.kafkanet
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  kafka-1:
    depends_on:
      - "zookeeper"
    image: "kf"
    ports:
      - "9092:9092"
      - "9093:9093" 
    networks:
      kafkanet:
        aliases:
          - kafka1.kafkanet
    volumes:
       - "./kafka-dist:/app"
       - "./configs:/configs"
       - "./certs/certificates:/certs"
       - "./example-commands.txt:/app/example-commands.txt"      
    command: ["/app/bin/kafka-server-start.sh", "/configs/kafka-server-1.properties"]
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  kafka-2:
    depends_on:
      - "zookeeper"
    image: "kf"
    ports:
      - "9094:9094"
      - "9095:9095"
    networks:
      kafkanet:
        aliases:
          - kafka2.kafkanet
    volumes:
       - "./kafka-dist:/app"
       - "./configs:/configs"
       - "./certs/certificates:/certs"
       - "./example-commands.txt:/app/example-commands.txt"       
    command: ["/app/bin/kafka-server-start.sh", "/configs/kafka-server-2.properties"]
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  kafka-3:
    depends_on:
      - "zookeeper"
    image: "kf"
    ports:
      - "9096:9096"
      - "9097:9097"
    networks:
      kafkanet:
        aliases:
          - kafka3.kafkanet
    volumes:
       - "./kafka-dist:/app"
       - "./configs:/configs"
       - "./certs/certificates:/certs"
       - "./example-commands.txt:/app/example-commands.txt"       
    command: ["/app/bin/kafka-server-start.sh", "/configs/kafka-server-3.properties"]
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  kafka-4:
    depends_on:
      - "zookeeper"
    image: "kf"
    ports:
      - "9098:9098"
      - "9099:9099"
    networks:
      kafkanet:
        aliases:
          - kafka4.kafkanet
    volumes:
       - "./kafka-dist:/app"
       - "./configs:/configs"
       - "./certs/certificates:/certs"
       - "./example-commands.txt:/app/example-commands.txt"       
    command: ["/app/bin/kafka-server-start.sh", "/configs/kafka-server-4.properties"]
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M