version: '3'
networks:
  kafkanet:
    driver: bridge
services:
  zookeeper:
    image: "zk"
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      kafkanet:
        aliases:
          - zookeeper.kafkanet
  kafka-1:
    depends_on:
      - "zookeeper"
    image: "kf"
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9093:9093" 
    networks:
      kafkanet:
        aliases:
          - kafka1.kafkanet       
    command: ["/app/bin/kafka-server-start.sh", "/configs/kafka-server-1.properties"]
  kafka-2:
    depends_on:
      - "zookeeper"
    image: "kf"
    container_name: kafka2
    ports:
      - "9094:9094"
      - "9095:9095"
    networks:
      kafkanet:
        aliases:
          - kafka2.kafkanet        
    command: ["/app/bin/kafka-server-start.sh", "/configs/kafka-server-2.properties"]
